Name:           ros-melodic-swri-console
Version:        1.1.0
Release:        0%{?dist}
Summary:        ROS swri_console package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/swri_console
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       qt5-qtbase
Requires:       qt5-qtbase-gui
Requires:       ros-melodic-rosbag-storage
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rosgraph-msgs
BuildRequires:  boost-devel
BuildRequires:  qt5-qtbase
BuildRequires:  qt5-qtbase-gui
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-rosbag-storage
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rosgraph-msgs

%description
A rosout GUI viewer developed at Southwest Research Insititute as an alternative
to rqt_console.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri May 11 2018 Elliot Johnson <elliot.johnson@swri.org> - 1.1.0-0
- Autogenerated by Bloom

